export const GET_MAP_DATA_REQUEST = 'GET_MAP_DATA_REQUEST';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
