export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';

export const CURRENT_TEMP_REQUEST = 'CURRENT_TEMP_REQUEST';
export const CURRENT_TEMP_ERROR = 'CURRENT_TEMP_ERROR';
export const CURRENT_TEMP_SUCCESS = 'CURRENT_TEMP_SUCCESS';
